controller_joint_names: ['', 'R_BCD_joint', 'L_BCD_joint', 'R_BBD1_joint', 'R_BBD2_joint', 'R_BBD3_joint', 'R_BBD4_joint', 'R_BBD5_joint', 'L_BBD1_joint', 'L_BBD2_joint', 'L_BBD3_joint', 'L_BBD4_joint', 'L_BBD5_joint', ]
